INSERT INTO AUTH_USER (ID, EMAIL, PASSWORD)
VALUES (RANDOM_UUID(), 'TEST@TEST.COM', '$2a$10$3LU0JFOUvgrHlNOE7nNVW.zBWWWukBJJWI.gAYc6fjPuIKRr6Cfra');

INSERT INTO AUTH_USER_ROLE (USER_ID, AUTH_ROLE)
VALUES (
    (SELECT ID FROM AUTH_USER WHERE EMAIL = 'TEST@TEST.COM'),
    'ADMIN'
);